### ISSUE TITLE
worker-ui displays Image-view

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/worker-ui#38] opened 2016-03-17 14:02 UTC
the worker-ui displays image for answer-type null in answer and rating

**Comment by simonkorz** [comment] 2016-03-17 14:17
I didn't know of the issuer here, but i spotted the error to. Was the same with answer view. fixed by commit 0b0ba21db9ed03cfbd699278671ece1471f55813

**Comment by LeanderK** [comment] 2016-03-17 14:47
still happens under rating view

**Comment by simonkorz** [comment] 2016-03-17 15:01
can't reproduce

**Comment by TheRittler** [comment] 2016-03-18 10:25
is this now still a bug or has this been fixed?

**Closed as completed** 2016-03-18 11:16 UTC
Labels: bug
